import "../styles/legal.scss";

export default function Terms() {
  return (
    <div className="legal-page">
      <div className="legal-content">
        <a href="/" className="legal-back">← Back to Content Intelligence</a>

        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: May 3, 2026</p>

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>By creating an account or using Content Intelligence App ("the App", "the Service"), you agree to these Terms of Service. If you do not agree, do not use the Service.</p>
          <p>The Service is operated by Andrés Pérez Díaz ("we", "us", "our"), a Colombian citizen operating as an individual until formal business registration.</p>
        </section>

        <section>
          <h2>2. Eligibility</h2>
          <p>You must be at least 18 years old to use this Service. By using the App, you confirm that you meet this requirement. We do not knowingly provide services to minors.</p>
        </section>

        <section>
          <h2>3. Early Access</h2>
          <p>The Service is currently in early access. Access is granted by invitation only. We reserve the right to limit, suspend, or revoke access at any time during this phase without prior notice.</p>
        </section>

        <section>
          <h2>4. Your Account</h2>
          <p>You are responsible for:</p>
          <ul>
            <li>Keeping your password secure and confidential</li>
            <li>All activity that occurs under your account</li>
            <li>Providing accurate information during registration</li>
          </ul>
          <p>You may not share your account with others or create accounts on behalf of third parties.</p>
        </section>

        <section>
          <h2>5. Use of the Service</h2>
          <p>You agree to use the Service only for lawful purposes. You may not:</p>
          <ul>
            <li>Use the Service to create content that infringes on third-party intellectual property rights</li>
            <li>Attempt to reverse engineer, copy, or replicate the Service</li>
            <li>Use automated tools to access the Service without our written permission</li>
            <li>Upload or transmit harmful, offensive, or illegal content</li>
          </ul>
        </section>

        <section>
          <h2>6. Content You Create</h2>
          <p><strong>Your ideas and content:</strong> All ideas, topics, and content records you create in the App remain yours. We do not claim ownership over the information you input.</p>
          <p><strong>AI-generated briefs and reports:</strong> The briefs and creative reports generated by the App are AI-assisted outputs based on patterns derived from your own content and ideas. They are provided as creative guides and orientation tools — not as finished content or definitive creative strategies.</p>
          <p><strong>Important notice on AI-generated content and copyright:</strong> AI-generated outputs may not be eligible for copyright protection under the laws of Colombia, the United States, or other jurisdictions. Current legal frameworks in many countries require human authorship for copyright eligibility. The briefs and reports provided by this Service are tools to support your creative process. The original content you create using these tools as a reference is your own work and may be eligible for copyright protection. We recommend consulting a legal professional if you have specific questions about intellectual property rights related to AI-assisted content.</p>
          <p>We do not claim intellectual property rights over the AI-generated outputs delivered to you through the Service.</p>
        </section>

        <section>
          <h2>7. Data and AI Training</h2>
          <p>We do not use your personal data or content to train AI models. The AI features of this Service are powered by Anthropic's Claude API. Your data is processed to generate responses but is not retained by Anthropic for model training purposes under their standard API terms.</p>
          <p>We may use aggregated, anonymized, and non-identifiable usage patterns to improve the Service over time.</p>
        </section>

        <section>
          <h2>8. Intellectual Property of the Service</h2>
          <p>The App, its design, features, and underlying technology are the intellectual property of Andrés Pérez Díaz. You may not copy, reproduce, or distribute any part of the Service without written permission.</p>
        </section>

        <section>
          <h2>9. Availability and Changes</h2>
          <p>We strive to keep the Service available but do not guarantee uninterrupted access. We may modify, suspend, or discontinue features at any time. We will make reasonable efforts to notify users of significant changes.</p>
        </section>

        <section>
          <h2>10. Disclaimer of Warranties</h2>
          <p>The Service is provided "as is" without warranties of any kind. We do not guarantee that the AI-generated content will be accurate, complete, or suitable for any specific purpose. Use the outputs of the Service at your own discretion.</p>
        </section>

        <section>
          <h2>11. Limitation of Liability</h2>
          <p>To the fullest extent permitted by Colombian law, Andrés Pérez Díaz shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>
        </section>

        <section>
          <h2>12. Termination</h2>
          <p>We may terminate or suspend your account if you violate these Terms. You may delete your account at any time by contacting us.</p>
        </section>

        <section>
          <h2>13. Governing Law</h2>
          <p>These Terms are governed by the laws of the Republic of Colombia. Any disputes shall be resolved under Colombian jurisdiction.</p>
        </section>

        <section>
          <h2>14. Contact</h2>
          <p>For questions about these Terms, contact us at: <a href="mailto:andres@content-intel.app">andres@content-intel.app</a></p>
        </section>
      </div>
    </div>
  );
}
